#! /bin/sh

# Appends the theme generated by wal to the terminator config so that applications
# opened with -e will share the same colorscheme
colors="$(< "${HOME}/.cache/wal/colors")"
q='"'
palette=$(echo $q$colors$q | awk '{gsub(/ /,":");print}')
sed -i '/palette = /c\'"    palette = $palette"'' ${HOME}/.config/terminator/config

# Takes a blurry screenshot of the desktop to be used for xlunch background
scrot /tmp/xlunch_bg.png
convert /tmp/xlunch_bg.png -blur 5x5 /tmp/xlunch_bg_blurred.png
